apiVersion: apps/v1
kind: Deployment
metadata:
  name: solana-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solana
  template:
    metadata:
      labels:
        app: solana
    spec:
      containers:
      - name: solana
        image: anuragbagri112/airdrop_app:latest
        ports:
          - containerPort: 5173
        imagePullPolicy: Always