apiVersion: v1
kind: Service
metadata:
  name: solana-service
spec:
  selector:
    app: solana
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30007
  type: NodePort